// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBlog.Infrastructure.EntityFramework.Entities;

#nullable disable

namespace MovieBlog.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    [Migration("20220418112523_Added comment entity")]
    partial class Addedcommententity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommentId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.ListToWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("ToWatch");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.MovieList", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ListId");

                    b.HasIndex("ListId");

                    b.ToTable("MoviesList");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Assessment")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdListToWatch")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Comment", b =>
                {
                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.Comment", null)
                        .WithMany("Children")
                        .HasForeignKey("CommentId");

                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.Review", null)
                        .WithMany("Comments")
                        .HasForeignKey("ReviewId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.ListToWatch", b =>
                {
                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.User", "Owner")
                        .WithOne("ToWatch")
                        .HasForeignKey("MovieBlog.Infrastructure.EntityFramework.Entities.ListToWatch", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.MovieList", b =>
                {
                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.ListToWatch", "List")
                        .WithMany("MoviesLists")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.Movie", "Movie")
                        .WithMany("MovieLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Review", b =>
                {
                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.User", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBlog.Infrastructure.EntityFramework.Entities.Movie", "RatedMovie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("RatedMovie");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Comment", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.ListToWatch", b =>
                {
                    b.Navigation("MoviesLists");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Movie", b =>
                {
                    b.Navigation("MovieLists");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.Review", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MovieBlog.Infrastructure.EntityFramework.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reviews");

                    b.Navigation("ToWatch")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
